#!/bin/bash


# 2021-06-04

# bcftools ver 1.12
# htslib is a suite of programs for interacting with high-throughput sequencing data. 



# Links:
# http://www.htslib.org
# http://www.htslib.org/download/



MODULE_NAME=bcftools
VERSION=1.12
MODULES_DIR=$HOME/software/modules
MODULESFILES_DIR=$HOME/software/modulesfiles


# ---------------------------------------------------------------------
# Create the module
# ---------------------------------------------------------------------


mkdir -p $MODULES_DIR/$MODULE_NAME/$VERSION
cd $MODULES_DIR/$MODULE_NAME/$VERSION

# Download the source code here: bcftools-1.12.tar.bz2.
# (The “Source code” downloads links below are generated by GitHub and are incomplete 
# as they don't bundle HTSlib and are missing some generated files.)

wget https://github.com/samtools/bcftools/releases/download/${VERSION}/bcftools-${VERSION}.tar.bz2
tar -xvjf bcftools-${VERSION}.tar.bz2


cd bcftools-${VERSION}

module purge
module load xz-utils/5.2.3_gcc7.2.0
module load bzip2/1.0.6-gnu6.1.0_PIC
module load gcc/7.2.0

./configure --prefix=$MODULES_DIR/$MODULE_NAME/$VERSION

make -j 16
make install





# ---------------------------------------------------------------------
# Create the modulefile
# ---------------------------------------------------------------------

mkdir -p $MODULESFILES_DIR/$MODULE_NAME
cd $MODULESFILES_DIR/$MODULE_NAME




cat > $VERSION <<EOF
#%Module######################################################################

module		 load xz-utils/5.2.3_gcc7.2.0
module		 load bzip2/1.0.6-gnu6.1.0_PIC
prepend-path PATH "$MODULES_DIR/$MODULE_NAME/$VERSION/bin"


EOF





# ---------------------------------------------------------------------
# Create the modulefile default version
# ---------------------------------------------------------------------


# Set the version
cat > .version <<ENDOFMESSAGE
#%Module
set ModulesVersion "$VERSION"

ENDOFMESSAGE






# ---------------------------------------------------------------------
# Update permissions (if you want to share the module)
# ---------------------------------------------------------------------


# Make all directories readable and executable
find $MODULES_DIR/$MODULE_NAME -type d -print0 | xargs -0 chmod a+rx
find $MODULESFILES_DIR/$MODULE_NAME -type d -print0 | xargs -0 chmod a+rx

# Make all files readable
find $MODULES_DIR/$MODULE_NAME -type f -print0 | xargs -0 chmod a+r
find $MODULESFILES_DIR/$MODULE_NAME -type f -print0 | xargs -0 chmod a+r

# Make all files, that are already executable, readable and executable
find $MODULES_DIR/$MODULE_NAME -type f -executable -print0 | xargs -0 chmod a+rx
# Note: there are no executable files in the modulesfiles directory







