#!/bin/bash

# 2021-08-10



MODULE_NAME=pindel
VERSION=20170508
MODULES_DIR=$HOME/software/modules
MODULESFILES_DIR=$HOME/software/modulesfiles


#######################################################################
# Install in modules dir
#######################################################################


mkdir -p $MODULES_DIR/$MODULE_NAME/$VERSION
cd $MODULES_DIR/$MODULE_NAME/$VERSION

# ---------------------------------------------------------------------
# First, download and install htslib (old version to work with Pindel)
# ---------------------------------------------------------------------
# The htslib-1.4.0.tar.bz2 download is the full source code release. The "Source code"
# downloads are generated by GitHub and are incomplete as they don't bundle HTSlib and 
# are missing some generated files.


wget https://github.com/samtools/htslib/releases/download/1.4/htslib-1.4.tar.bz2
tar -xvjf htslib-1.4.tar.bz2


module purge
module load xz-utils/5.2.3_gcc7.2.0
module load bzip2/1.0.6-gnu6.1.0_PIC
module load gcc/4.9.2

mkdir -p $MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4
cd $MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4
./configure --prefix=$MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4

make -j 16
make install



# ---------------------------------------------------------------------
# Download and install Pindel
# ---------------------------------------------------------------------

cd $MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4

# Get source code
# latest commit: May 8, 2017
# https://github.com/genome/pindel/commit/b706fba

git clone --recursive https://github.com/genome/pindel.git
cd $MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4/pindel
git checkout b706fba



# install dependencies
module purge
module load gcc/4.9.2


# Install Pindel
./INSTALL $MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4







# ---------------------------------------------------------------------
# Create the modulefile
# ---------------------------------------------------------------------

mkdir -p $MODULESFILES_DIR/$MODULE_NAME
cd $MODULESFILES_DIR/$MODULE_NAME




cat > $VERSION <<EOM
#%Module######################################################################

module load gcc/4.9.2
prepend-path PATH "$MODULES_DIR/$MODULE_NAME/$VERSION/htslib-1.4/pindel"

EOM





# ---------------------------------------------------------------------
# Create the modulefile default version
# ---------------------------------------------------------------------


# Set the version
cat > .version <<EOM
#%Module
set ModulesVersion "$VERSION"

EOM





# ---------------------------------------------------------------------
# Update permissions (if you want to share the module)
# ---------------------------------------------------------------------

# Make all files readable; directories readable and executable
chmod a+rxs $MODULES_DIR/$MODULE_NAME
find $MODULES_DIR/$MODULE_NAME/$VERSION -type d -print0 | xargs -0 chmod a+rxs
find $MODULES_DIR/$MODULE_NAME/$VERSION -type f -print0 | xargs -0 chmod a+r
chmod a+rxs $MODULESFILES_DIR/$MODULE_NAME
find $MODULESFILES_DIR/$MODULE_NAME -type f -print0 | xargs -0 chmod a+r

# Make all files, that were already executable for the user, readable and executable for all
find $MODULES_DIR/$MODULE_NAME/$VERSION -type f -executable -print0 | xargs -0 chmod a+rx

